---
- name: Install Packages using Chocolatey and Ansible Tower
  hosts: windows
  gather_facts: false
- name: Install notepadplusplus version 6.6
  win_chocolatey:
    name: notepadplusplus
    version: '6.6'
